# Generated by Django 5.2.15 on 2026-06-27 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalaryStructure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("base_salary", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "pay_frequency",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly"),
                            ("biweekly", "Bi-weekly"),
                            ("weekly", "Weekly"),
                        ],
                        default="monthly",
                        max_length=20,
                    ),
                ),
                (
                    "housing_allowance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "transport_allowance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "other_allowances",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("tax_rate", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ("effective_date", models.DateField()),
                (
                    "employee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salary",
                        to="employees.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payslip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("base_salary", models.DecimalField(decimal_places=2, max_digits=12)),
                ("allowances", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("deductions", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("tax", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("net_pay", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("processed", "Processed"), ("paid", "Paid")],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payslips",
                        to="employees.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["-period_start"],
                "unique_together": {("employee", "period_start", "period_end")},
            },
        ),
    ]
